-- USE CHINOOK;
 
-- Esercizio 1 Recuperate tutte le tracce che abbiano come genere “Pop” o “Rock”. 
SELECT
	TR.NAME AS CANZONE,
    GE.NAME AS GENERE
FROM TRACK AS TR
INNER JOIN GENRE AS GE
ON TR.GENREID = GE.GENREID
WHERE GE.NAME IN ('POP', 'ROCK');

-- Esercizio 2 Elencate tutti gli artisti e/o gli album che inizino con la lettera “A”. 
-- ARTISTI CHE INIZIANO CON LA LETTERA A
SELECT
	NAME
FROM  
	ARTIST
WHERE NAME LIKE 'A%';

-- ALBUM CHE INIZIANO CON LA LETTERA A
SELECT 
	TITLE
FROM
	ALBUM
WHERE TITLE LIKE 'A%';

-- Esercizio 3 Elencate tutte le tracce che hanno come genere “Jazz” o che durano meno di 3 minuti. 
SELECT 
	TR.NAME AS CANZONE,
    TR.MILLISECONDS AS DURATA_CANZONE,
    GE.NAME AS GENERE
FROM TRACK AS TR
INNER JOIN GENRE AS GE
ON TR.GENREID = GE.GENREID
WHERE GE.NAME = 'JAZZ'
OR TR.MILLISECONDS IN (SELECT MILLISECONDS
						FROM TRACK
						WHERE MILLISECONDS < 180000);

-- Esercizio 4 Recuperate tutte le tracce più lunghe della durata media.
SELECT 
		NAME AS CANZONE,
		MILLISECONDS/60000 AS DURATA_CANZONE
FROM TRACK
WHERE MILLISECONDS > (SELECT DISTINCT AVG(MILLISECONDS)
						FROM TRACK);

-- Esercizio 5 Individuate i generi che hanno tracce con una durata media maggiore di 4 minuti. 
SELECT GE.
		NAME AS GENERE,
		AVG(TR.MILLISECONDS/60000) AS DURATA_MEDIA
FROM GENRE AS GE
INNER JOIN TRACK AS TR
ON GE.GENREID = TR.GENREID
WHERE TR.MILLISECONDS/60000 > 4
GROUP BY GE.NAME
ORDER BY AVG(TR.MILLISECONDS/60000);

-- Esercizio 6 Individuate gli artisti che hanno rilasciato più di un album. 
SELECT 
		AR.NAME AS ARTISTA,
		COUNT(AL.TITLE) AS NUMERO_ALBUM
FROM ARTIST AS AR
INNER JOIN ALBUM AS AL
ON AR.ARTISTID = AL.ARTISTID
GROUP BY AR.NAME
HAVING COUNT(AL.TITLE)>1
ORDER BY COUNT(AL.TITLE);

-- Esercizio 7 Trovate la traccia più lunga in ogni album. 
SELECT 	
		AL.TITLE AS TITOLO_ALBUM,
        MAX(TR.MILLISECONDS/60000) AS DURATA_MAX_TRACCIA
FROM TRACK AS TR
INNER JOIN ALBUM AS AL
ON TR.ALBUMID = AL.ALBUMID
GROUP BY AL.TITLE
ORDER BY MAX(TR.MILLISECONDS/60000);

-- Esercizio 8 Individuate la durata media delle tracce per ogni album. 
SELECT 	
		AL.TITLE AS TITOLO_ALBUM,
        AVG(TR.MILLISECONDS/60000) AS DURATA_MEDIA_TRACCIA
FROM TRACK AS TR
INNER JOIN ALBUM AS AL
ON TR.ALBUMID = AL.ALBUMID
GROUP BY AL.TITLE
ORDER BY AVG(TR.MILLISECONDS/60000);

-- Esercizio 9 Individuate gli album che hanno più di 20 tracce e mostrate il nome dell’album e il numero di tracce in esso contenute.
SELECT 
		AL.TITLE,
		COUNT(TR.NAME)
FROM ALBUM AS AL
INNER JOIN TRACK AS TR
ON AL.ALBUMID = TR.ALBUMID
GROUP BY AL.TITLE
HAVING COUNT(TR.NAME) > 20
ORDER BY COUNT(TR.NAME);

